### PR TITLE
iclr paper

### PR DESCRIPTION
**Pull request by eric8607242**
Hi!
I add some of the papers accepted by ICLR 2021.

### CODE REVIEW

**Comment by eric8607242** [comment]
Hi, I make a one-shot NAS example repo. I am not sure whether the repo has enough quality to merge into this repo as a reference blog. Can you help me to check this repo to decide merge or not?  Very thanks!

In the repo, I cover each component (e.g., search space, search strategy, and performance estimation). And each component can be incorporated flexibly into various baselines. For example, the search space of FBNet with uniform sampling training and the random search can be implemented easily in this repo.

For search space, I implement the supernet of FBNet, ProxylessNAS, and SPOS.
For supernet training, I implement uniform sampling, fairness sampling, and differentiable (specific for DNAS).
For search strategy, I implement differentiable search, random search, and evolution algorithm.

**Review by D-X-Y — APPROVED** [review]
Thanks for contributing

**Comment by D-X-Y** [comment]
It seems that the goal of your repo is similar to Frank Hutter's NASLib while his repo is more comprehensive. You can have a look at NASLib~

**Comment by eric8607242** [comment]
Thanks for the invaluable comment! I will keep updating to be more comprehensive.

**Pull request merged**
